# Generated by Django 5.2.4 on 2025-08-03 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50)),
                ('billing_duration', models.PositiveIntegerField(help_text='Duration in months for monthly plans or years for yearly plans')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tenant',
                'verbose_name_plural': 'Tenants',
                'db_table': 'tenants',
                'constraints': [models.UniqueConstraint(fields=('name',), name='unique_tenant_name_constraint')],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('tenant_admin', 'Tenant Admin'), ('tenant_user', 'Tenant User'), ('platform_admin', 'Platform Admin')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'indexes': [models.Index(fields=['email'], name='email_index'), models.Index(fields=['role'], name='role_index')],
                'constraints': [models.UniqueConstraint(fields=('email',), name='unique_email_constraint')],
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('trial', 'Trial'), ('paused', 'Paused'), ('renewal', 'Renewal'), ('failed', 'Failed')], max_length=50)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_subscriptions', to='api.plans')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_subscriptions', to='api.tenants')),
                ('created_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_subscriptions', to='api.users')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
            },
        ),
        migrations.AddField(
            model_name='plans',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_plans', to='api.users'),
        ),
        migrations.CreateModel(
            name='LimitPolicies',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('max_users', 'Max Users')], max_length=50)),
                ('limit', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_limit_policies', to='api.users')),
            ],
            options={
                'verbose_name': 'Limit Policy',
                'verbose_name_plural': 'Limit Policies',
                'db_table': 'limit_policies',
            },
        ),
        migrations.CreateModel(
            name='UserTenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_users', to='api.tenants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tenants', to='api.users')),
            ],
            options={
                'verbose_name': 'User Tenant',
                'verbose_name_plural': 'User Tenants',
                'db_table': 'user_tenants',
            },
        ),
        migrations.CreateModel(
            name='PlansLimitPolicies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('limit_policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_policy_plans', to='api.limitpolicies')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_limit_policies', to='api.plans')),
            ],
            options={
                'verbose_name': 'Plan Limit Policy',
                'verbose_name_plural': 'Plan Limit Policies',
                'db_table': 'plans_limit_policies',
                'unique_together': {('plan', 'limit_policy')},
            },
        ),
        migrations.CreateModel(
            name='Usages',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('max_users', 'Max Users')], max_length=50)),
                ('value', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_usages', to='api.subscriptions')),
            ],
            options={
                'verbose_name': 'Usage',
                'verbose_name_plural': 'Usages',
                'db_table': 'usages',
                'indexes': [models.Index(fields=['metric'], name='usage_metric_index'), models.Index(fields=['subscription_id'], name='usage_subscription_index')],
                'constraints': [models.UniqueConstraint(fields=('subscription_id', 'metric'), name='unique_usage_constraint')],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptions',
            index=models.Index(fields=['status'], name='status_index'),
        ),
        migrations.AddIndex(
            model_name='subscriptions',
            index=models.Index(fields=['created_by_user_id'], name='created_by_user_index'),
        ),
        migrations.AddIndex(
            model_name='subscriptions',
            index=models.Index(fields=['plan_id'], name='plan_index'),
        ),
        migrations.AddIndex(
            model_name='subscriptions',
            index=models.Index(fields=['tenant_id'], name='tenant_index'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('created_by_user_id', 'plan_id', 'tenant_id'), name='unique_subscription_constraint'),
        ),
        migrations.AddConstraint(
            model_name='plans',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_plan_name_constraint'),
        ),
        migrations.AddIndex(
            model_name='limitpolicies',
            index=models.Index(fields=['metric'], name='metric_index'),
        ),
        migrations.AddConstraint(
            model_name='limitpolicies',
            constraint=models.UniqueConstraint(fields=('metric',), name='unique_limit_policy_metric_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='usertenants',
            unique_together={('user', 'tenant')},
        ),
    ]
