# Generated by Django 5.2.4 on 2025-08-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enable_rls'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='limitpolicies',
            name='unique_limit_policy_metric_constraint',
        ),
        migrations.AddConstraint(
            model_name='planslimitpolicies',
            constraint=models.UniqueConstraint(fields=('plan', 'limit_policy'), name='unique_plan_limit_policy_constraint'),
        ),
    ]
