# Generated by Django 5.2.4 on 2025-08-06 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_limitpolicies_unique_limit_policy_metric_constraint_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptions',
            name='unique_subscription_constraint',
        ),
        migrations.RemoveConstraint(
            model_name='usages',
            name='unique_usage_constraint',
        ),
        migrations.RemoveIndex(
            model_name='subscriptions',
            name='created_by_user_index',
        ),
        migrations.RemoveIndex(
            model_name='subscriptions',
            name='plan_index',
        ),
        migrations.RemoveIndex(
            model_name='subscriptions',
            name='tenant_index',
        ),
        migrations.RemoveIndex(
            model_name='usages',
            name='usage_subscription_index',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='created_by_user_id',
            new_name='created_by_user',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='plan_id',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='subscriptions',
            old_name='tenant_id',
            new_name='tenant',
        ),
        migrations.RenameField(
            model_name='usages',
            old_name='subscription_id',
            new_name='subscription',
        ),
        migrations.AddIndex(
            model_name='subscriptions',
            index=models.Index(fields=['created_by_user'], name='created_by_user_index'),
        ),
        migrations.AddIndex(
            model_name='subscriptions',
            index=models.Index(fields=['plan'], name='plan_index'),
        ),
        migrations.AddIndex(
            model_name='subscriptions',
            index=models.Index(fields=['tenant'], name='tenant_index'),
        ),
        migrations.AddIndex(
            model_name='usages',
            index=models.Index(fields=['subscription'], name='usage_subscription_index'),
        ),
        migrations.AddConstraint(
            model_name='subscriptions',
            constraint=models.UniqueConstraint(fields=('created_by_user', 'plan', 'tenant'), name='unique_subscription_constraint'),
        ),
        migrations.AddConstraint(
            model_name='usages',
            constraint=models.UniqueConstraint(fields=('subscription', 'metric'), name='unique_usage_constraint'),
        ),
    ]
