# Generated by Django 5.2.4 on 2025-08-06 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_subscriptions_unique_subscription_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
