# Generated by Django 5.2.4 on 2025-08-06 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_subscriptions_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_subscriptions', to='api.tenants'),
        ),
    ]
