# Generated by Django 5.2.5 on 2025-08-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_subscriptions_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitpolicies',
            name='metric',
            field=models.CharField(max_length=100),
        ),
    ]
